services:
  postgres:
    image: postgres
    container_name: postgres_signalsiege
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${SQL_USERNAME}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    volumes:
      - signal_siege_database:/var/lib/postgresql/data
    restart: always
  
  app:
    image: unveiledsafe8/signalsiege:v1.0
    container_name: app_signalsiege
    ports:
      - "8000:${SYSTEM_PORT}"
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always

volumes:
  signal_siege_database:
    driver: local