services:
  postgres:
    image: postgres
    container_name: postgres_signalsiege
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=signal_siege_database
    volumes:
      - signal_siege_database:/var/lib/postgresql/data
    restart: always
  
  app:
    build: .
    container_name: app_signalsiege
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always

volumes:
  signal_siege_database:
    driver: local